---
# hosts could have been "remote" or "all" as well
- hosts: meugrupolocal
  connection: local
  become: yes
  become_user: root
  tasks:
   #- name: Show facts available on the system
   # debug:
   #    var: ansible_facts
        
   - name: Remover o Nginx
     apt:
       name: nginx
       state: absent
       update_cache: false
     register: statusremocao
     
   - name: Mostrar statusremocao
     debug:
       var: statusremocao

   - name: Instalar o Nginx
     apt:
       name: nginx
       state: present
       update_cache: false
     when: statusremocao.failed == false
     register: statusinstalacao
     notify:
      - Iniciar modulo nginx

   - name: Mostrar statusinstalacao
     debug:
       var: statusinstalacao

  handlers:
   - name: Iniciar modulo nginx
     service:
       name: nginx
       state: started
       